### PR TITLE
Update tss-esapi version

### LINKED ISSUE #663: Parsec 1.1 fails to build with meta-security master branch
On 22.02 tmp2-tss was updated from 3.2.0 to 4.0.1 in meta-security.
https://gitlab.com/akuster/meta-security/-/commit/e188be029cdfdd18f993b0ae2b37d885cfbb191b

Since then Parsec builds fail with:
```
thread 'main' panicked at 'Unsupported TSS version: 4', /home/gitlab-runner/builds/CAxQb6fJ/0/akuster/meta-security/build/tmp/work/cortexa57-poky-linux/parsec-service/1.1.0-r0/cargo_home/bitbake/tss-esapi-7.1.0/build.rs:9:22
```
https://gitlab.com/akuster/meta-security/-/jobs/3818857216

https://github.com/parallaxsecond/rust-tss-esapi/blob/7205c4c825f6d299c7094714d7f5b7dd3fb2b5e9/tss-esapi/build.rs#L9

I can see that it’s fixed in the main branch of tss-esapi:
https://github.com/parallaxsecond/rust-tss-esapi/blob/1a02c8f5be18924bf67a2776f6c5f39dfbe6538a/tss-esapi/build.rs#L13

But, Parsec main branch still uses 7.1.0:
https://github.com/parallaxsecond/parsec/blob/838e93ae5477c3d3ba9223f823b765d8766e0b96/Cargo.toml#L32 (edited)

### PR DESCRIPTION
**Pull request by gowthamsk-arm**
The tmp2-tss version on meta-security has been updated to 4.0.1 from 3.2.0. This is not compatible with the current tss-esapi crate. The newer version 7.2.0 of the crate is now available which resolves the issue.

Signed-off-by: Gowtham Suresh Kumar <gowtham.sureshkumar@arm.com>

Closes #663

### CODE REVIEW

**Comment by anta5010** [comment]
Have you tried to update Parsec yocto recipe and build it with master branch of meta-security?

**Comment by gowthamsk-arm** [comment]
I didn't update the yocto recipe and test it there. Was planning on testing that part during the release work. We can keep this MR open until then.

**Comment by anta5010** [comment]
> I didn't update the yocto recipe and test it there. Was planning on testing that part during the release work. We can keep this MR open until then.

I've tested a temp recipe for this fix and found another issue:
- Parsec cargo.lock contains only 0.57.0 and 0.59.2 versions of bindgen:
https://github.com/parallaxsecond/parsec/blob/main/Cargo.lock#L112
- but, tss-esapi 0.7.2 requires 0.63.0
https://github.com/parallaxsecond/rust-tss-esapi/blob/5fbdcafe4025826d0a3cef88b113aaf5c9600fa2/tss-esapi-sys/Cargo.toml#L16

We use cargo-bitbake to update Parsec Yocto recipes and it uses cargo.lock from Pasrec repo.
As a result Parsec Yocto build fails because bindgen 0.63.0 is missing from dependencies list.
 
It's possible to include bindgen 0.63.0 into the recipe manually. But, I think before the next Parsec release crate dependencies need to be reviewed in all all cargo.toml-s and the cargo.lock updated.

**Review by adamjohnstonarm — APPROVED** [review]
LGTM

**Review by ionut-arm — APPROVED** [review]

**Comment by gowthamsk-arm** [comment]
Included in #671

**Pull request closed without merging**
