### PR TITLE
Fix problem reported by Clippy (rust 1.62)

### PR DESCRIPTION
**Pull request by mohamedasaker-arm**
Signed-off-by: Mohamed Omar Asaker <mohamed.omarasaker@arm.com>

### CODE REVIEW

**Comment by anta5010** [comment]
Is this change compatible with old version of rust. Like 1.58.1 we use in Yocto?

**Comment by ionut-arm** [comment]
> Is this change compatible with old version of rust. Like 1.58.1 we use in Yocto?

We do have CI checks for that sort of thing, so it should be caught if there's a regression.

**Comment by mohamedasaker-arm** [comment]
Hi @anta5010 good point!
I've just used 1.58.1 and run the following commands as test
`cargo clippy --all-targets --features=all-providers -- -D clippy::all -D clippy::cargo`
`cargo clippy --all-targets --features=pkcs11-provider --manifest-path e2e_tests/Cargo.toml -- -D clippy::all -D clippy::cargo`
and I see no complaints on these changes. Do you have another check in mind?

**Comment by ionut-arm** [comment]
Just to confirm: the CI checks for [1.57](https://github.com/parallaxsecond/parsec/blob/main/ci.sh#L223) as MSRV, so anything past that should work fine.

**Review by ionut-arm — APPROVED** [review]
LGTM

**Pull request merged**
