### PR TITLE
Add dependency cross matching

### PR DESCRIPTION
**Pull request by tgonzalezorlandoarm**
* Add a script to check for mismatches in dependencies in the repository.
* Add a dependency mismatcher job that checks whether any dependencies have more than one versions.

Mismatches are two different versions of the same dependency

### CODE REVIEW

**Comment by tgonzalezorlandoarm** [comment]
I ran the following check on my fork:
https://github.com/tgonzalezorlandoarm/parsec/actions/runs/6748176585

**Review by gowthamsk-arm — DISMISSED** [review]
Thanks. LGTM.

**Comment by tgonzalezorlandoarm** [comment]
Ran a new check with the new changes and it passes:
https://github.com/tgonzalezorlandoarm/parsec/actions/runs/6771105440

**Review by gowthamsk-arm — APPROVED** [review]

**Comment by tgonzalezorlandoarm** [comment]
#360

**Pull request merged**
