### PR TITLE
structopt: Migrate to clap

### PR DESCRIPTION
**Pull request by tgonzalezorlandoarm**
According to https://github.com/TeXitoi/structopt/issues/525,
    structopt has entered maintenance mode, and clap should be used
    for new development.
    
     * Migrate to clap so that nightly builds succeed as well.

### CODE REVIEW

**Comment by tgonzalezorlandoarm** [comment]
Please note this changes the exception list for dependency mismatch for parsec to include heck, which seems unavoidable

**Comment by tgonzalezorlandoarm** [comment]
This is supposed to solve the issues in https://github.com/parallaxsecond/parsec/actions/runs/8319327971/job/22762462593

**Comment by tgonzalezorlandoarm** [comment]
I triggered a nightly run in here: https://github.com/tgonzalezorlandoarm/parsec/actions/runs/8328515939

**Comment by tgonzalezorlandoarm** [comment]
The failure in the CI mismatch check is in teh parsec-tool and is expected, as the same change is coming with this pr: https://github.com/parallaxsecond/parsec-tool/pull/125

**Comment by tgonzalezorlandoarm** [comment]
Please refer to https://github.com/TeXitoi/structopt/issues/525 for more information

**Review by gowthamsk-arm — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
